#!/usr/bin/env python

# NOTE ON PERMISSIONS:
# Have to type the below line first for permission change to run
# sudo chmod a+rw /dev/i2c-*

# CREDITS:
# 

# IMPORT:
import time
import board
import GPIO                # chage to GPIO

import rospy
from digital_servo import Start, Stop, Step

def servo(START, STOP, STEP):
    
    
    
    
def talker():

    # MAIN PART OF PUBLISHING:
    pub = rospy.Publisher('example/servo', *package*, queue_size=50)    # Change: pub = rospy.Publisher('name_of_component', package_used, queue_size=50)
    rospy.init_node('servo_motor_node', anonymous=True)                 # Change: rospy.init_node('name_of_node', anonymous=True)

    # TIME KEEPING:
    start_time = rospy.Time.now()
    current_time = rospy.Time.now()
    last_time = rospy.Time.now()
    rate = rospy.Rate(10)  # 10hz while not rospy.is_shutdown(): odom = Odometry()

    # FUNCTIONS OF SPECIFIC COMPONENT:
    while not rospy.is_shutdown():

        s = servo()                           # Change: for specific component
        i.header.stamp = rospy.Time.now()
        i.header.frame_id = 'base_link'     # All nodes need to have the same name, maybe change to main_frame_id"

        print(state)

        time.sleep(0.5)  # sleep for 0.5 seconds

        # PUBLISH RESULTS:
        pub.publish(s)
        
# NAME THIS SECTION:
if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass
